### ISSUE TITLE
I got SOTA result with hparam search

### ISSUE THREAD

**Issue by lukaspetersson** [lss-1138/SparseTSF#1]
I put the Sparse TSF in the [PatchTST repo](https://github.com/yuqinie98/PatchTST/tree/main) and did a hyper parameter search. I got a MSE of 0.31 for 336 prediction length which is better than SOTA. Am I doing something wrong or are the SOTA results not optimized?

**Comment by lss-1138** [comment]
Thank you for your interest. The results reported in the paper were not obtained through hyperparameter  search. The hyper parameter we focused on, `period_len`, is determined by the characteristics of the dataset. As for `batch_size` and `learning_rate`, we uniformly chose relatively consistent values. So, it's possible that you achieved better results through hyperparameter search.
