### ISSUE TITLE
Is the paper in arXiv final version? 

### ISSUE THREAD

**Issue by mb-Ma** [lss-1138/SparseTSF#5]
I noticed that SparseTSF adopts the channel-independent strategy in Section 3.1. 

However, The channel-dependent strategy is used in the source code. 

Is there a conflict between them?

**Comment by lss-1138** [comment]
Thank you for your question. The channel-independent strategy used in the source code `models/SparseTSF.py` is indeed a channel-independent approach.

In fact, there are two types of channel-independent strategies: one involves modeling with **shared parameters** between channels (as used in PatchTST), and the other involves modeling with **non-shared parameters** between channels (completely channel-independent), which means using independent models for each channel (e.g., setting the parameter `individual` to `True` in the DLinear model).

In SparseTSF, we use the former channel-independent strategy, where parameters are shared between each channel. This is consistent with the description in Section 3.1, which states: "the CI method finds a **shared** function $f$ for each univariate series." There is no modeling of relationships between channels involved here.

**Comment by mb-Ma** [comment]
Thank you for your quick feedback. 
But, confusedly, it seems a conflict if shared and non-shared parameters both are channel-independent strategies. 
In other words, what is the channel-dependent strategy in the context?

Could you explain more, please?

**Comment by lss-1138** [comment]
A channel-dependent strategy, such as the ones adopted by Informer and Autoformer, mixes the data from different channels at the model's input. Additionally, models like Crossformer and iTransformer explicitly allow data interaction between channels during modeling. Therefore, the key distinction between channel-independent and channel-dependent strategies is whether there is interaction between the information of different channels. The channel-independent strategy with shared parameters does not involve interaction between channels.

I recommend reading this paper: [The Capacity and Robustness Trade-off: Revisiting the Channel Independent Strategy for Multivariate Time Series Forecasting](https://arxiv.org/pdf/2304.05206). This paper provides a detailed study on the differences, advantages, and disadvantages of channel-dependent and channel-independent strategies.

**Comment by mb-Ma** [comment]
I agree with the claim that distinguishes channel-dependent and -independent strategies from the interaction perspective. Personality, the share-parameter strategy is an implicit interaction between channels. 

I will check this from the paper that you mentioned above. Thank you for your reply, again. :-)
